# Generated by Django 3.1.6 on 2021-02-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='featured',
            new_name='featured',
        ),
    ]
